CREATE DATABASE homemarket
ON PRIMARY (
NAME = N'homemarket',
FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\homemarket.mdf',
SIZE = 5120 KB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 1024 KB
)
LOG ON (
NAME = N'homemarket_log',
FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\homemarket_log.ldf',
SIZE = 1024 KB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 10 %
)
GO

ALTER DATABASE homemarket
SET
ANSI_NULL_DEFAULT OFF,
ANSI_NULLS OFF,
ANSI_PADDING OFF,
ANSI_WARNINGS OFF,
ARITHABORT OFF,
AUTO_CLOSE OFF,
AUTO_CREATE_STATISTICS ON,
AUTO_SHRINK OFF,
AUTO_UPDATE_STATISTICS ON,
AUTO_UPDATE_STATISTICS_ASYNC OFF,
COMPATIBILITY_LEVEL = 110,
CONCAT_NULL_YIELDS_NULL OFF,
CURSOR_CLOSE_ON_COMMIT OFF,
CURSOR_DEFAULT GLOBAL,
DATE_CORRELATION_OPTIMIZATION OFF,
DB_CHAINING OFF,
HONOR_BROKER_PRIORITY OFF,
MULTI_USER,
NUMERIC_ROUNDABORT OFF,
PAGE_VERIFY CHECKSUM,
PARAMETERIZATION SIMPLE,
QUOTED_IDENTIFIER OFF,
READ_COMMITTED_SNAPSHOT OFF,
RECOVERY FULL,
RECURSIVE_TRIGGERS OFF,
TRUSTWORTHY OFF
WITH ROLLBACK IMMEDIATE
GO

ALTER DATABASE homemarket
COLLATE SQL_Latin1_General_CP1_CI_AS
GO

ALTER DATABASE homemarket
SET DISABLE_BROKER
GO

ALTER DATABASE homemarket
SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE homemarket
SET FILESTREAM (NON_TRANSACTED_ACCESS = OFF)
GO

ALTER AUTHORIZATION ON DATABASE :: homemarket TO dev_user
GO